#' Static Visualization of Richness and Trait Maps
#'
#' @description
#' This function is the dedicated plotting tool for outputs from `richness_here()`.
#' It automatically handles single-layer rasters (e.g., species richness) and
#' multi-layer rasters (e.g., multiple biological traits or flags), creating
#' a standardized visual using **ggplot2**.
#'
#' @param grid (SpatRaster) A raster object generated by `richness_here()`.
#' @param low_color (character) color for the lowest values. Default is "blue".
#' @param mid_color (character) color for the midpoint. Default is "yellow".
#' @param high_color (character) color for the highest values. Default is "red".
#' @param alpha (numeric) transparency of the grid (0-1). Default is 0.8.
#' @param continent (SpatVector) optional polygon layer for boundaries.
#' @param continent_fill (character) fill color for continents. Default is "gray70".
#' @param continent_linewidth (numeric) line width for continent boundaries.
#' Default is 0.3.
#' @param continent_border (character) color of the continent polygon borders.
#' Default is "white".
#' @param ocean_fill (character) background color for the ocean. Default is "aliceblue".
#' @param extension (SpatExtent or numeric) optional map extent.
#' @param theme_plot (theme) a `ggplot2` theme object.
#'
#' @returns A ggplot object. If the grid has multiple layers, they will be
#' displayed using `facet_wrap`.
#'
#' @importFrom ggplot2 ggplot aes geom_tile scale_fill_gradient2 coord_sf xlab ylab theme element_rect labs
#' @importFrom terra as.data.frame crop unwrap ext nlyr
#' @importFrom sf st_as_sf
#' @importFrom patchwork wrap_plots
#'
#' @export
#'
#' @examples
#' # Load example data
#' data("occ_flagged", package = "RuHere")
#'
#' # Simple richness map
#' r_records <- richness_here(occ_flagged, summary = "records", res = 2)
#' ggrid_here(r_records)
#'
#' # Multi-layer map (e.g., density of specific flags)
#' # Let's see where 'florabr' and 'duplicated' flags are concentrated
#' r_flags <- richness_here(occ_flagged, summary = "records",
#'                          field = c("florabr_flag", "iucn_flag"),
#'                          fun = function(x, ...) sum(!x, na.rm = TRUE), res = 2)
#' ggrid_here(r_flags)
#'
ggrid_here <- function(grid, low_color = "blue", mid_color = "yellow",
                       high_color = "red", alpha = 0.8, continent = NULL,
                       continent_fill = "gray70", continent_linewidth = 0.3,
                       continent_border = "white", ocean_fill = "aliceblue",
                       extension = NULL,
                       theme_plot = ggplot2::theme_minimal()) {

  if (!inherits(grid, "SpatRaster")) {
    stop("'grid' must be a SpatRaster object from richness_here().", call. = FALSE)
  }

  if (is.null(continent)) {
    continent <- terra::unwrap(getExportedValue("RuHere", "world"))
    continent <- sf::st_as_sf(continent)
  }

  if (is.null(extension)) {
    extension <- as.vector(terra::ext(grid))
  }

  grid_cropped <- terra::crop(grid, terra::ext(extension))

  layer_names <- names(grid_cropped)
  plot_list <- lapply(layer_names, function(layer) {

    df_layer <- terra::as.data.frame(grid_cropped[[layer]], xy = TRUE, na.rm = TRUE)
    colnames(df_layer)[3] <- "Value"

    title_clean <- gsub("_", " ", layer)
    title_clean <- paste0(toupper(substr(title_clean, 1, 1)), substr(title_clean, 2, nchar(title_clean)))

    p_sub <- ggplot2::ggplot() +
      ggplot2::geom_sf(data = continent, fill = continent_fill,
                       linewidth = continent_linewidth, col = continent_border) +
      ggplot2::geom_tile(data = df_layer,
                         ggplot2::aes(x = .data$x, y = .data$y, fill = .data$Value),
                         alpha = alpha) +
      ggplot2::scale_fill_gradient2(name = layer,
                                    low = low_color, mid = mid_color, high = high_color,
                                    midpoint = median(df_layer$Value, na.rm = TRUE)) +
      ggplot2::coord_sf(xlim = c(extension[1], extension[2]),
                        ylim = c(extension[3], extension[4]), expand = FALSE) +
      ggplot2::labs(title = title_clean, x = "Longitude", y = "Latitude") +
      theme_plot +
      ggplot2::theme(panel.background = ggplot2::element_rect(fill = ocean_fill, colour = NA))

    return(p_sub)
  })

  if (length(plot_list) == 1) {
    return(plot_list[[1]])
  } else {
    return(patchwork::wrap_plots(plot_list))
  }

}
