# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moranfast <- function(x, weight, scaled = FALSE, na_rm = FALSE, alternative = "two.sided") {
    .Call(`_RuHere_moranfast`, x, weight, scaled, na_rm, alternative)
}

kde_rcpp <- function(fishnet, points, bw, kernel, scaled, decay, weights) {
    .Call(`_RuHere_kde_rcpp`, fishnet, points, bw, kernel, scaled, decay, weights)
}

